name: EReport

on:
  push:
    branches: [ main ] #sesuaikan dengan branch repositoryl

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol:  ftps
          passive : true
          server: 151.243.222.70    #ip server hosting anda- contoh menggunakan ip hostingdata.id
          username: random@arcueia.my.id   #sesuaikan dengan username dan password ftp anda
          password: randompassword
          # exclude accepts a multiline string. Using a block scalar avoids YAML alias parsing.
          exclude: |
            **/.git/**
            **/node_modules/**
